version: '2.2'

services:
  server:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/postgres
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: "unless-stopped"
  db:
    image: postgres:12
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
