basePath: /api/v1
definitions:
  article.Dto:
    properties:
      content:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: integer
      slug:
        type: string
      thumbnail:
        type: string
      title:
        type: string
      updateAt:
        type: string
      updateBy:
        type: string
      version:
        type: integer
    type: object
  article.Payload:
    properties:
      content:
        type: string
      createdBy:
        type: string
      id:
        type: integer
      thumbnail:
        type: string
      title:
        type: string
      updateBy:
        type: string
    type: object
  comment.Dto:
    properties:
      content:
        type: string
      createdAt:
        type: string
      createdBy:
        type: string
      id:
        type: integer
      idArticle:
        type: integer
      num:
        type: integer
      parentId:
        type: integer
      type:
        type: string
      updateAt:
        type: string
      updateBy:
        type: string
      version:
        type: integer
    type: object
  comment.PayLoad:
    properties:
      content:
        type: string
      idArticle:
        type: integer
      parentId:
        type: integer
      type:
        type: string
      userId:
        type: string
    type: object
  dchat.Data:
    properties:
      body:
        example: tin nhan moi
        type: string
      createdAt:
        type: string
      groupId:
        type: integer
      id:
        type: integer
      idContinueOldMess:
        type: integer
      numChildMess:
        type: integer
      parentID:
        type: integer
      sender:
        example: "null"
        type: string
      socketId:
        example: "9999"
        type: string
      status:
        example: "null"
        type: string
      type:
        type: string
      updatedAt:
        type: string
    type: object
  dchat.Message:
    properties:
      client:
        type: string
      data:
        $ref: '#/definitions/dchat.Data'
        type: object
      type:
        example: send_text
        type: string
    type: object
  groups.Dto:
    properties:
      description:
        type: string
      id:
        type: integer
      nameGroup:
        type: string
      owner:
        type: string
      private:
        type: boolean
      thumbnail:
        type: string
      type:
        type: string
    type: object
  groups.PayLoad:
    properties:
      description:
        type: string
      nameGroup:
        type: string
      private:
        type: boolean
      type:
        type: string
      users:
        items:
          type: string
        type: array
    type: object
  userdetail.Dto:
    properties:
      first:
        type: string
      fullName:
        type: string
      hostName:
        type: string
      id:
        type: string
      last:
        type: string
      role:
        type: string
      socketId:
        type: string
      status:
        type: string
      userName:
        type: string
    type: object
  utils.ResponseBool:
    properties:
      result:
        type: boolean
    type: object
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: "This is swagger for chat server.\nlocal:\t  http://localhost:5000/.\nstaging:    http://vdat-mcsvc-chat-staging.vdatlab.com/.\nproduction: https://vdat-mcsvc-chat.vdatlab.com/."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Chat server API
  version: "0.1"
paths:
  /api/v1/all-article:
    get:
      consumes:
      - application/json
      description: Get all article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/article.Dto'
            type: array
      summary: Get all article
      tags:
      - article
  /api/v1/article:
    get:
      consumes:
      - application/json
      description: Get the article corresponding to the input user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/article.Dto'
            type: array
      summary: Get article by userid
      tags:
      - article
    post:
      consumes:
      - application/json
      description: Insert new article
      parameters:
      - description: insert article
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/article.Payload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/article.Dto'
      summary: Insert article
      tags:
      - article
  /api/v1/article/{idArticle}:
    delete:
      consumes:
      - application/json
      description: Delete the article corresponding to the input idArticle
      parameters:
      - description: ID of the article to be updated
        in: path
        name: idArticle
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseBool'
      summary: Delete article by idArticle
      tags:
      - article
    get:
      consumes:
      - application/json
      description: Get the article corresponding to the input title
      parameters:
      - description: name search by title
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/article.Dto'
            type: array
      summary: Get article by title
      tags:
      - article
    put:
      consumes:
      - application/json
      description: Update the article corresponding to the input idArticle
      parameters:
      - description: ID of the article to be updated
        in: path
        name: idArticle
        required: true
        type: integer
      - description: update article
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/article.Payload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/article.Dto'
      summary: Update article by idArticle
      tags:
      - article
  /api/v1/comment:
    post:
      consumes:
      - application/json
      description: Insert new comment
      parameters:
      - description: insert comment
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/comment.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.Dto'
      summary: Insert comment
      tags:
      - comment
  /api/v1/comment/{id}:
    delete:
      consumes:
      - application/json
      description: Delete comment by id comment
      parameters:
      - description: ID of the comment to be updated
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseBool'
      summary: Delete comment by idCmt
      tags:
      - comment
    put:
      consumes:
      - application/json
      description: Update the Comment corresponding to the input id
      parameters:
      - description: ID of the comment to be updated
        in: path
        name: id
        required: true
        type: integer
      - description: update comment
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/comment.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.Dto'
      summary: Update Comment by idCmt
      tags:
      - comment
  /api/v1/comment/{idArticle}:
    get:
      consumes:
      - application/json
      description: Get the comment corresponding to the input articleId
      parameters:
      - description: ID of the article to be find
        in: path
        name: idArticle
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/comment.Dto'
            type: array
      summary: Get comment by Article id
      tags:
      - comment
  /api/v1/comment/parent/{idParent}:
    get:
      consumes:
      - application/json
      description: Get the comment corresponding to the input parentId
      parameters:
      - description: ID of the parent comment to be find
        in: path
        name: idParent
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/comment.Dto'
            type: array
      summary: Get comment by parent id
      tags:
      - comment
  /api/v1/comment/rely:
    post:
      consumes:
      - application/json
      description: Insert new comment rely
      parameters:
      - description: insert rely comment
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/comment.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.Dto'
      summary: Insert comment rely
      tags:
      - comment
  /api/v1/groups:
    get:
      consumes:
      - application/json
      description: Get all groups
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/groups.Dto'
            type: array
      summary: Get all groups
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: create a new groups
      parameters:
      - description: Create groups
        in: body
        name: groupPayLoad
        required: true
        schema:
          $ref: '#/definitions/groups.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.Dto'
      summary: Create a new groups
      tags:
      - groups
  /api/v1/groups/{idGroup}:
    delete:
      consumes:
      - application/json
      description: Delete the group corresponding to the input idGroup
      parameters:
      - description: ID of the group to be updated
        in: path
        name: idGroup
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
      summary: Delete group identified by the given idGroup
      tags:
      - groups
    put:
      consumes:
      - application/json
      description: Update the group corresponding to the input groupId
      parameters:
      - description: ID of the group to be updated
        in: path
        name: idGroup
        required: true
        type: integer
      - description: update groups
        in: body
        name: groupPayLoad
        required: true
        schema:
          $ref: '#/definitions/groups.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/groups.Dto'
      summary: Update group by groupId
      tags:
      - groups
  /api/v1/groups/{idGroup}/members:
    delete:
      consumes:
      - application/json
      description: delete user to group
      parameters:
      - description: ID of the group to be add user
        in: path
        name: idGroup
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: delete user to group
      tags:
      - groupUser
    get:
      consumes:
      - application/json
      description: Get all member groups
      parameters:
      - description: ID of the group to be updated
        in: path
        name: idGroup
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/userdetail.Dto'
              type: array
            type: array
      summary: Get all member groups
      tags:
      - groupUser
    patch:
      consumes:
      - application/json
      description: add user to group
      parameters:
      - description: ID of the group to be updated
        in: path
        name: idGroup
        required: true
        type: integer
      - description: add user to group
        in: body
        name: groupPayLoad
        required: true
        schema:
          $ref: '#/definitions/groups.PayLoad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: add user to group
      tags:
      - groupUser
  /api/v1/groups/{idGroup}/members/{userId}:
    delete:
      consumes:
      - application/json
      description: delete user to group by admin
      parameters:
      - description: ID group
        in: path
        name: idGroup
        required: true
        type: integer
      - description: ID user want delete
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: delete user to group by admin
      tags:
      - groupUser
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: find user by keyword
      parameters:
      - description: name search by keyword
        in: query
        name: keyword
        type: string
      - description: page
        in: query
        name: page
        type: integer
      - description: pageSize
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/userdetail.Dto'
            type: array
      summary: find users by keyword
      tags:
      - user
  /api/v1/user/info:
    get:
      consumes:
      - application/json
      description: check user api
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userdetail.Dto'
      summary: check user api
      tags:
      - user
  /api/v1/user/online:
    delete:
      consumes:
      - application/json
      description: user logout api
      parameters:
      - description: hostName
        in: query
        name: hostName
        type: string
      - description: socketId
        in: query
        name: socketId
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: user logout
      tags:
      - user
  /message/{socketId}:
    get:
      consumes:
      - application/json
      description: chat group by websocket
      parameters:
      - description: socketId to know client
        in: path
        name: socketId
        required: true
        type: string
      - description: token to be join chat
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      summary: Chat websocket
      tags:
      - dchat
    post:
      consumes:
      - application/json
      description: |-
        NOTE
        Event For Send Message

        "type":"subcribe_group" - to open the group the person has joined

        "type":"send_text" - to send text from current client to users in that group

        "type":"load_old_mess" - to load continues history message in group
      parameters:
      - description: socketId to know client
        in: path
        name: socketId
        required: true
        type: string
      - description: token to be join chat
        in: query
        name: token
        required: true
        type: string
      - description: Works based on field event type (read NOTE)
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/dchat.Message'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dchat.Message'
      summary: Chat websocket
      tags:
      - dchat
schemes:
- http
- https
swagger: "2.0"
